### ISSUE TITLE
ID→ツイート時間を求める計算式

### ISSUE THREAD

**Issue by kgtkr** [sk2sat/sksat_bot#1]
多くのサイトでは`((id >> 22) + 1288834974657)`と紹介されていますが、このbotは`((id >> 22) + 1288834974567)`となっています。
これは意図的な物でしょうか？それともバグでしょうか？
この計算式違いにより-90msの差が出てしまっているようです。

**Comment by sksat** [comment]
Twitterで教えてもらったものをそのまま使っていたので確かに間違っているかもしれません．確認します．

**Comment by sksat** [comment]
https://github.com/twitter/snowflake/blob/scala_28/src/main/scala/com/twitter/service/snowflake/IdWorker.scala
Twitterのstatus id生成に使われているsnowflake（正確には，現在のものは公開されていないが実際はやっていることはほぼ同じ，とのこと）のコードを参照したところ，確かに基点となっているunix timeはご指摘の通り```1288834974657```のようです．修正します．
