### ISSUE TITLE
"1640"などで誤差が100ms未満だとツイート時間の表示がおかしくなる

### ISSUE THREAD

**Issue by kgtkr** [sk2sat/sksat_bot#2]
確認はしていませんが、10ms未満でも同様の問題が発生する可能性があります

# 問題のツイート
### URL
https://twitter.com/sksat_bot/status/956233640895131648
### 本文
>03:34:00.8000
>0.08秒遅延
### 予想される本文
```
03:34:00.0800
0.08秒遅延
```

### URL
https://twitter.com/sksat_bot/status/956431444640808960
### 本文
>16:40:00.9300
>0.093秒遅延
## 予想される本文
```
16:40:00.0930
0.093秒遅延
```

**Comment by sksat** [comment]
数値を文字列にしたものを雑に結合していたようです．

**Comment by sksat** [comment]
修正しました．

**Comment by kgtkr** [comment]
誤差がマイナスでも表示がおかしくなります
https://twitter.com/sksat_bot/status/956793830988177408
